import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Script from "next/script";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "InstaViewPro",
  description: "Generated by create next app",
  icons: {
    icon: "/Favicon2.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}

        {/* UTMYFY */}
        <Script
          src="https://cdn.utmify.com.br/scripts/utms/latest.js"
          data-utmify-prevent-xcod-sck
          data-utmify-prevent-subids
          async
          defer
        ></Script>
        <Script
          id="utmify-pixel"
          strategy="afterInteractive"
          dangerouslySetInnerHTML={{
            __html: `
      window.pixelId = "6832a0bbd523704c18758478";
      var a = document.createElement("script");
      a.setAttribute("async", "");
      a.setAttribute("defer", "");
      a.setAttribute("src", "https://cdn.utmify.com.br/scripts/pixel/pixel.js");
      document.head.appendChild(a);
    `,
          }}
        />

      {/* Meta Pixel Script */}
<Script id="facebook-pixel" strategy="afterInteractive">
  {`
    !(function(f, b, e, v, n, t, s) {
      if (f.fbq) return;
      n = f.fbq = function() {
        n.callMethod ? n.callMethod.apply(n, arguments) : n.queue.push(arguments);
      };
      if (!f._fbq) f._fbq = n;
      n.push = n;
      n.loaded = true;
      n.version = '2.0';
      n.queue = [];
      t = b.createElement(e);
      t.async = true;
      t.src = 'https://connect.facebook.net/en_US/fbevents.js';
      s = b.getElementsByTagName(e)[0];
      s.parentNode.insertBefore(t, s);
    })(window, document, 'script');

    fbq('init', '1081176860598734');
    fbq('track', 'PageView');
  `}
</Script>
        {/* Noscript fallback */}
      {/* <Script
  id="meta-noscript"
  strategy="afterInteractive"
  dangerouslySetInnerHTML={{
    __html: `
      (function() {
        var noscript = document.createElement('noscript');
        var img = document.createElement('img');
        img.height = 1;
        img.width = 1;
        img.style = 'display:none';
        img.src = "https://www.facebook.com/tr?id=1081176860598734&ev=PageView&noscript=1";
        noscript.appendChild(img);
        document.body.appendChild(noscript);
      })();
    `,
  }}
/> */}
<Script
  id="debug-fbq"
  strategy="afterInteractive"
  dangerouslySetInnerHTML={{
    __html: `
      setTimeout(() => {
        console.log("🔍 fbq is", typeof fbq);
      }, 3000);
    `,
  }}
/>
      </body>
    </html>
  );
}
